import { StyleSheet } from "react-native";
import { colors } from "../theme/colors";

export const styles = StyleSheet.create({
  screenWrapper: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 140,
  },
  userCard: {
    position: "relative",
    alignItems: "center",
    backgroundColor: colors.surface,
    borderRadius: 20,
    paddingVertical: 18,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  creditsPillTop: {
    position: "absolute",
    top: 12,
    right: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "rgba(234, 179, 8, 0.12)",
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(234, 179, 8, 0.3)",
  },
  creditsPillText: {
    color: "#eab308",
    fontSize: 11,
    fontWeight: "700",
  },
  avatarWrap: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: colors.surfaceLight,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 8,
    marginTop: 4,
    overflow: "hidden",
  },
  avatarImage: {
    width: 76,
    height: 76,
    borderRadius: 38,
  },
  verifiedBadge: {
    position: "absolute",
    bottom: -2,
    right: -2,
    backgroundColor: colors.surface,
    borderRadius: 10,
  },
  nameRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    minHeight: 28,
  },
  userName: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  editNameButton: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: colors.surfaceLight,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
  },
  userEmail: {
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 2,
  },
  locationRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 6,
  },
  locationText: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  statsContainer: {
    flexDirection: "row",
    backgroundColor: colors.surface,
    borderRadius: 18,
    marginTop: 14,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: 12,
  },
  statBox: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    paddingVertical: 4,
  },
  statBorderHorizontal: {
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: colors.border,
  },
  ratingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  statValue: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  statLabel: {
    fontSize: 11,
    color: colors.textSecondary,
    marginTop: 2,
  },
  statChevron: {
    marginTop: 3,
  },
  aboutCard: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    padding: 14,
    marginTop: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  aboutHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 6,
  },
  aboutTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  aboutText: {
    fontSize: 12,
    color: colors.textSecondary,
    lineHeight: 18,
  },
  logoutButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 24,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: "#3f1d24",
  },
  logoutText: {
    color: "#ef4444",
    fontSize: 14,
    fontWeight: "600",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.72)",
    justifyContent: "flex-end",
  },
  modalSheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 36,
    maxHeight: "85%",
    borderTopWidth: 1,
    borderColor: colors.border,
  },
  sheetHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  sheetTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  sheetTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  sheetSub: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  editAvatarSection: {
    alignItems: "center",
    marginVertical: 12,
  },
  editAvatarWrap: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.surfaceLight,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.accentBlue,
    position: "relative",
    overflow: "hidden",
  },
  editAvatarImage: {
    width: 80,
    height: 80,
    borderRadius: 40,
  },
  cameraIconBadge: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: colors.accentBlue,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: colors.surface,
  },
  editAvatarHint: {
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 6,
  },
  inputLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.textSecondary,
    marginBottom: 6,
    marginTop: 8,
  },
  inputBox: {
    backgroundColor: colors.surfaceLight,
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 44,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
  },
  inputBoxArea: {
    height: 90,
    paddingVertical: 10,
  },
  inputField: {
    color: colors.textPrimary,
    fontSize: 14,
    paddingVertical: 0,
  },
  inputFieldArea: {
    height: "100%",
  },
  dropdownSelectorBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.surfaceLight,
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 44,
    borderWidth: 1,
    borderColor: colors.border,
  },
  dropdownSelectorText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: "500",
  },
  editButtonsRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 20,
  },
  cancelBtn: {
    flex: 1,
    height: 46,
    borderRadius: 12,
    backgroundColor: colors.surfaceLight,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
  },
  cancelBtnText: {
    color: colors.textSecondary,
    fontWeight: "600",
    fontSize: 14,
  },
  saveBtn: {
    flex: 2,
    height: 46,
    borderRadius: 12,
    backgroundColor: colors.accentBlue,
    alignItems: "center",
    justifyContent: "center",
  },
  saveBtnText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 14,
  },
  dropdownModalBox: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 18,
    width: "100%",
    maxHeight: "65%",
    borderWidth: 1,
    borderColor: colors.border,
  },
  subModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.75)",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  comunaItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.surfaceLight,
  },
  comunaItemActive: {
    backgroundColor: colors.surfaceLight,
    borderRadius: 8,
  },
  comunaItemText: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  comunaItemTextActive: {
    color: colors.accentBlue,
    fontWeight: "700",
  },
  pubTabBar: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    marginBottom: 10,
  },
  pubTabButton: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 10,
    position: "relative",
  },
  pubTabText: {
    fontSize: 13,
    fontWeight: "500",
    color: colors.textMuted,
  },
  pubTabTextActive: {
    color: colors.textPrimary,
    fontWeight: "700",
  },
  pubActiveIndicator: {
    position: "absolute",
    bottom: -1,
    left: 20,
    right: 20,
    height: 2,
    backgroundColor: colors.accentBlue,
    borderRadius: 1,
  },
  reviewCard: {
    backgroundColor: colors.surfaceLight,
    borderRadius: 14,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  reviewHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  reviewUserRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  reviewAvatar: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  reviewAuthor: {
    fontSize: 13,
    fontWeight: "600",
    color: colors.textPrimary,
  },
  starsRow: {
    flexDirection: "row",
    gap: 2,
  },
  reviewComment: {
    fontSize: 12,
    color: colors.textSecondary,
    lineHeight: 16,
    marginBottom: 4,
  },
  reviewDate: {
    fontSize: 10,
    color: colors.textMuted,
  },
  taskCard: {
    backgroundColor: colors.surfaceLight,
    borderRadius: 14,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  taskHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  headerLeftRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  badge: {
    backgroundColor: colors.accentBlueBg,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  badgeText: {
    color: colors.accentBlue,
    fontSize: 11,
    fontWeight: "600",
  },
  photosBadgeTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: colors.surface,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.border,
  },
  photosBadgeText: {
    fontSize: 10,
    fontWeight: "700",
    color: colors.accentBlue,
  },
  taskMonto: {
    color: colors.accentGreen,
    fontSize: 14,
    fontWeight: "700",
  },
  taskTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.textPrimary,
    marginBottom: 8,
  },
  taskFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  taskDate: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  badgeAcceptedTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "rgba(34, 197, 94, 0.12)",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  badgeAcceptedText: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.accentGreen,
  },
  badgeCompletedTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: colors.surface,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  badgeCompletedText: {
    fontSize: 11,
    fontWeight: "600",
    color: colors.textMuted,
  },
  badgeApplicantsTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: colors.accentBlueBg,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  badgeApplicantsText: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.accentBlue,
  },
  noApplicantsText: {
    fontSize: 11,
    color: colors.textMuted,
  },
  subModalBox: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 18,
    maxHeight: "75%",
    borderWidth: 1,
    borderColor: colors.border,
  },
  postulantesImagesContainer: {
    marginBottom: 10,
  },
  miniPhotoRow: {
    flexDirection: "row",
  },
  postulantesThumbWrap: {
    width: 64,
    height: 64,
    borderRadius: 10,
    marginRight: 8,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: colors.border,
  },
  postulantesThumb: {
    width: "100%",
    height: "100%",
  },
  managementActionsRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 12,
  },
  btnFinalizarTarea: {
    flex: 1.4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.accentGreen,
    height: 42,
    borderRadius: 12,
    gap: 6,
  },
  btnFinalizarTareaText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "700",
  },
  btnCancelarAcuerdo: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceLight,
    height: 42,
    borderRadius: 12,
    gap: 4,
    borderWidth: 1,
    borderColor: "#7f1d1d",
  },
  btnCancelarAcuerdoText: {
    color: "#ef4444",
    fontSize: 12,
    fontWeight: "600",
  },
  btnDarDeBajaTarea: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceLight,
    height: 38,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 6,
    marginBottom: 10,
  },
  btnDarDeBajaTareaText: {
    color: "#ef4444",
    fontSize: 12,
    fontWeight: "600",
  },
  emptyApplicantsBox: {
    alignItems: "center",
    paddingVertical: 24,
    gap: 8,
  },
  emptyApplicantsTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.textSecondary,
  },
  applicantCard: {
    backgroundColor: colors.surfaceLight,
    borderRadius: 14,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  applicantHeaderTouchable: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  applicantUserRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  applicantAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
  },
  applicantNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  applicantName: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  applicantRatingRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  applicantRatingText: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  applicantJobsText: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  badgeAcceptedSmall: {
    backgroundColor: "rgba(34, 197, 94, 0.12)",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  badgeAcceptedSmallText: {
    fontSize: 10,
    fontWeight: "700",
    color: colors.accentGreen,
  },
  applicantMsg: {
    fontSize: 12,
    color: colors.textSecondary,
    lineHeight: 16,
    marginBottom: 10,
  },
  applicantActionsRow: {
    flexDirection: "row",
    gap: 8,
  },
  btnReject: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    height: 36,
    borderRadius: 10,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 4,
  },
  btnRejectText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#ef4444",
  },
  btnAccept: {
    flex: 1.6,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    height: 36,
    borderRadius: 10,
    backgroundColor: colors.accentBlue,
    gap: 4,
  },
  btnAcceptText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#ffffff",
  },
  btnWhatsAppApplicant: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    height: 40,
    borderRadius: 10,
    backgroundColor: "#22c55e",
    gap: 6,
  },
  btnWhatsAppApplicantText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#ffffff",
  },
  applicantProfileBox: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: colors.border,
    maxHeight: "80%",
  },
  applicantProfileHeader: {
    alignItems: "center",
    paddingTop: 4,
    paddingBottom: 8,
  },
  applicantProfileAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.surfaceLight,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 6,
    borderWidth: 1,
    borderColor: colors.border,
  },
  applicantProfileName: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  applicantProfileComuna: {
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 2,
  },
  applicantProfileAboutBox: {
    backgroundColor: colors.surfaceLight,
    borderRadius: 12,
    padding: 10,
    marginVertical: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  applicantProfileAboutTitle: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.textPrimary,
    marginBottom: 3,
  },
  applicantProfileAboutText: {
    fontSize: 12,
    color: colors.textSecondary,
    lineHeight: 16,
  },
  miniTabBar: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    marginBottom: 8,
  },
  miniTabButton: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 8,
    position: "relative",
  },
  tabHeaderLabel: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  miniTabText: {
    fontSize: 12,
    fontWeight: "500",
    color: colors.textMuted,
  },
  miniTabTextActive: {
    color: colors.textPrimary,
    fontWeight: "700",
  },
  miniActiveIndicator: {
    position: "absolute",
    bottom: -1,
    left: 14,
    right: 14,
    height: 2,
    backgroundColor: colors.accentBlue,
    borderRadius: 1,
  },
  tabScrollBox: {
    maxHeight: 140,
    marginBottom: 10,
  },
  miniReviewCard: {
    backgroundColor: colors.surfaceLight,
    borderRadius: 10,
    padding: 8,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: colors.border,
  },
  miniReviewHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 2,
  },
  miniReviewAuthor: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  miniReviewComment: {
    fontSize: 11,
    color: colors.textSecondary,
    lineHeight: 15,
  },
  miniReviewDate: {
    fontSize: 9,
    color: colors.textMuted,
    marginTop: 2,
  },
  miniHistoryCard: {
    backgroundColor: colors.surfaceLight,
    borderRadius: 10,
    padding: 8,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: colors.border,
  },
  miniHistoryHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  miniHistoryTitle: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.textPrimary,
  },
  miniHistoryMonto: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.accentGreen,
  },
  miniHistoryDate: {
    fontSize: 10,
    color: colors.textSecondary,
    marginTop: 2,
  },
  emptyTabText: {
    fontSize: 11,
    color: colors.textMuted,
    fontStyle: "italic",
    textAlign: "center",
    paddingVertical: 14,
  },
  applicantProfileActionsRow: {
    flexDirection: "row",
    marginTop: 4,
  },
  reviewModalDesc: {
    fontSize: 13,
    color: colors.textSecondary,
    textAlign: "center",
    marginTop: 4,
    marginBottom: 16,
  },
  starSelectRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 12,
    marginBottom: 16,
  },
  reviewInputBox: {
    backgroundColor: colors.surfaceLight,
    borderRadius: 12,
    padding: 12,
    height: 80,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 10,
  },
  reviewInputField: {
    color: colors.textPrimary,
    fontSize: 13,
    paddingVertical: 0,
    height: "100%",
  },
  reviewModalNotice: {
    fontSize: 11,
    color: colors.textMuted,
    fontStyle: "italic",
    textAlign: "center",
    lineHeight: 15,
    marginBottom: 16,
  },
  btnConfirmarFinalizacion: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.accentBlue,
    height: 46,
    borderRadius: 12,
    gap: 8,
  },
  btnConfirmarFinalizacionText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
  },
  balanceCard: {
    backgroundColor: colors.surfaceLight,
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  balanceLabel: {
    fontSize: 12,
    color: colors.textSecondary,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  balanceNumber: {
    fontSize: 24,
    fontWeight: "800",
    color: "#eab308",
    marginVertical: 4,
  },
  balanceSubtext: {
    fontSize: 11,
    color: colors.textMuted,
    textAlign: "center",
    lineHeight: 15,
  },
  packagesTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.textPrimary,
    marginBottom: 10,
  },
  packageCard: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: colors.surfaceLight,
    padding: 14,
    borderRadius: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.border,
    position: "relative",
  },
  packageCardPopular: {
    borderColor: "#eab308",
    backgroundColor: "rgba(234, 179, 8, 0.05)",
  },
  popularBadge: {
    position: "absolute",
    top: -9,
    right: 14,
    backgroundColor: "#eab308",
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 6,
  },
  popularBadgeText: {
    fontSize: 9,
    fontWeight: "800",
    color: "#000000",
  },
  packageInfo: {
    flex: 1,
  },
  packageCreditsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  packageCredits: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.textPrimary,
  },
  packageDesc: {
    fontSize: 11,
    color: colors.textSecondary,
    marginTop: 2,
  },
  buyButtonWrap: {
    backgroundColor: colors.accentBlue,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 10,
  },
  packagePrice: {
    fontSize: 13,
    fontWeight: "700",
    color: "#ffffff",
  }
});