import { StyleSheet } from 'react-native';
import { colors } from '../theme/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingHorizontal: 20,
    paddingTop: 14,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 14,
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surfaceLight,
    borderRadius: 20,
    paddingHorizontal: 14,
    height: 44,
    borderWidth: 1,
    borderColor: colors.border,
  },
  searchInput: {
    flex: 1,
    color: colors.textPrimary,
    fontSize: 14,
    marginLeft: 8,
    paddingVertical: 0,
  },
  filterButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.surfaceLight,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  filterButtonActive: {
    borderColor: colors.accentBlue,
    backgroundColor: colors.accentBlueBg,
  },
  filterDotActive: {
    position: 'absolute',
    top: 9,
    right: 10,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.accentBlue,
  },
  listContent: {
    paddingTop: 2,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: colors.border,
    position: 'relative',
  },
  cardFeatured: {
    borderColor: '#eab308',
    backgroundColor: 'rgba(234, 179, 8, 0.03)',
  },
  featuredBadgeTop: {
    position: 'absolute',
    top: -8,
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#eab308',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 6,
  },
  featuredBadgeText: {
    fontSize: 9,
    fontWeight: '800',
    color: '#000000',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  headerLeftRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  badge: {
    backgroundColor: colors.accentBlueBg,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  badgeText: {
    color: colors.accentBlue,
    fontSize: 12,
    fontWeight: '600',
  },
  photosBadgeTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: colors.surfaceLight,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.border,
  },
  photosBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.accentBlue,
  },
  statusTag: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  statusTagPending: {
    backgroundColor: 'rgba(234, 179, 8, 0.15)',
  },
  statusTagPendingText: {
    color: '#eab308',
    fontSize: 10,
    fontWeight: '700',
  },
  statusTagAccepted: {
    backgroundColor: 'rgba(34, 197, 94, 0.15)',
  },
  statusTagAcceptedText: {
    color: colors.accentGreen,
    fontSize: 10,
    fontWeight: '700',
  },
  statusTagCompleted: {
    backgroundColor: colors.surfaceLight,
  },
  statusTagCompletedText: {
    color: colors.textMuted,
    fontSize: 10,
    fontWeight: '700',
  },
  cardMonto: {
    color: colors.accentGreen,
    fontSize: 16,
    fontWeight: '700',
  },
  cardTitle: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 10,
  },
  cardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  footerItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  footerText: {
    color: colors.textSecondary,
    fontSize: 12,
  },
  mapContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 140,
    paddingHorizontal: 30,
  },
  mapTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.textPrimary,
    marginTop: 12,
  },
  mapSubtitle: {
    fontSize: 13,
    color: colors.textSecondary,
    textAlign: 'center',
    marginTop: 6,
  },
  floatingButtonContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pluxeeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1d4ed8',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 8,
    gap: 8,
    elevation: 6,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 6,
  },
  pluxeeButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: -0.2,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.72)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 20,
    paddingHorizontal: 20,
    maxHeight: '86%',
    borderTopWidth: 1,
    borderColor: colors.border,
  },
  sheetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  sheetTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  detailCategoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  detailScrollContent: {
    paddingVertical: 14,
  },
  detailTitle: {
    fontSize: 19,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 12,
  },
  detailImagesContainer: {
    marginBottom: 16,
  },
  detailImagesScroll: {
    flexDirection: 'row',
    marginTop: 8,
  },
  detailImageCard: {
    width: 160,
    height: 120,
    borderRadius: 12,
    marginRight: 10,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surfaceLight,
  },
  detailImage: {
    width: 160,
    height: 120,
    borderRadius: 14,
  },
  detailMetaCard: {
    flexDirection: 'row',
    backgroundColor: colors.surfaceLight,
    borderRadius: 14,
    padding: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  detailMetaItem: {
    flex: 1,
    alignItems: 'center',
  },
  detailMetaDivider: {
    width: 1,
    backgroundColor: colors.border,
  },
  detailMetaLabel: {
    fontSize: 10,
    color: colors.textSecondary,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  detailPrice: {
    fontSize: 17,
    fontWeight: '800',
    color: colors.accentGreen,
    marginTop: 2,
  },
  detailComuna: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textPrimary,
    marginTop: 2,
  },
  detailDate: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textPrimary,
    marginTop: 2,
  },
  detailSectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: 8,
    marginTop: 8,
  },
  userRowDetail: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.surfaceLight,
    padding: 12,
    borderRadius: 14,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  userLeftInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  userAvatarDetail: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  userNameDetail: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  userSubDetail: {
    fontSize: 11,
    color: colors.accentBlue,
    fontWeight: '600',
  },
  detailBodyText: {
    fontSize: 14,
    color: colors.textPrimary,
    lineHeight: 21,
    marginBottom: 14,
    backgroundColor: colors.surfaceLight,
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  detailActionContainer: {
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  btnPrimaryAction: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accentBlue,
    height: 50,
    borderRadius: 14,
    gap: 8,
  },
  btnActionText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '700',
  },
  ownerBox: {
    backgroundColor: 'rgba(59, 130, 246, 0.08)',
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.25)',
    gap: 8,
  },
  ownerText: {
    color: colors.textSecondary,
    fontSize: 12,
    textAlign: 'center',
  },
  btnDeleteOwner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(239, 68, 68, 0.12)',
    height: 42,
    borderRadius: 10,
    gap: 6,
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.3)',
  },
  btnDeleteOwnerText: {
    color: '#ef4444',
    fontSize: 13,
    fontWeight: '700',
  },
  pendingActionWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(234, 179, 8, 0.1)',
    padding: 14,
    borderRadius: 14,
    gap: 10,
    borderWidth: 1,
    borderColor: 'rgba(234, 179, 8, 0.3)',
  },
  pendingActionText: {
    flex: 1,
    color: '#eab308',
    fontSize: 12,
    fontWeight: '600',
  },
  btnRetirarPostulacion: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    gap: 4,
  },
  btnRetirarPostulacionText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#ef4444',
  },
  whatsappButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#22c55e',
    height: 50,
    borderRadius: 14,
    gap: 8,
  },
  completedBadgeWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceLight,
    height: 48,
    borderRadius: 14,
    gap: 8,
  },
  completedBadgeText: {
    color: colors.accentGreen,
    fontSize: 13,
    fontWeight: '700',
  },

  // Modal de Filtros
  sheetBody: {
    paddingVertical: 14,
  },
  filterSectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textPrimary,
    marginVertical: 8,
  },
  dropdownButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.surfaceLight,
    paddingHorizontal: 14,
    height: 48,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 14,
  },
  dropdownInner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  dropdownButtonText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '500',
  },
  sliderHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 6,
  },
  sliderValueBadge: {
    color: colors.accentBlue,
    fontSize: 14,
    fontWeight: '700',
  },
  sliderStepsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 8,
  },
  stepItem: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: colors.surfaceLight,
  },
  stepItemActive: {
    backgroundColor: colors.accentBlue,
  },
  stepText: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  stepTextActive: {
    color: '#ffffff',
    fontWeight: '700',
  },
  sheetFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    gap: 12,
  },
  btnReset: {
    flex: 1,
    height: 46,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceLight,
  },
  btnResetText: {
    color: colors.textSecondary,
    fontWeight: '600',
    fontSize: 14,
  },
  btnApply: {
    flex: 2,
    height: 46,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.accentBlue,
  },
  btnApplyText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 14,
  },

  // Modal Sub-Selectores y Perfil Solicitante
  dropdownOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  dropdownModal: {
    width: '100%',
    maxHeight: '65%',
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: colors.border,
  },
  dropdownHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    marginBottom: 8,
  },
  dropdownTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  dropdownItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.surfaceLight,
  },
  dropdownItemActive: {
    backgroundColor: colors.surfaceLight,
    borderRadius: 8,
    paddingHorizontal: 8,
  },
  dropdownItemText: {
    fontSize: 14,
    color: colors.textSecondary,
  },
  dropdownItemTextActive: {
    color: colors.accentBlue,
    fontWeight: '700',
  },

  // Ficha de perfil del solicitante
  solicitanteModalBox: {
    width: '100%',
    maxHeight: '75%',
    backgroundColor: colors.surface,
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    borderColor: colors.border,
  },
  solicitanteHeader: {
    alignItems: 'center',
    paddingVertical: 10,
  },
  solicitanteAvatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: colors.surfaceLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  solicitanteName: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  solicitanteComuna: {
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 2,
  },
  solicitanteRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 6,
    backgroundColor: 'rgba(234, 179, 8, 0.1)',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
  },
  solicitanteRatingText: {
    color: '#eab308',
    fontSize: 12,
    fontWeight: '700',
  },
  solicitanteAboutBox: {
    backgroundColor: colors.surfaceLight,
    borderRadius: 12,
    padding: 12,
    marginVertical: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  solicitanteAboutTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textSecondary,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  solicitanteAboutText: {
    fontSize: 12,
    color: colors.textPrimary,
    lineHeight: 17,
  },
  solicitanteReviewCard: {
    backgroundColor: colors.surfaceLight,
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  solicitanteReviewHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  solicitanteReviewAuthor: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  solicitanteReviewComment: {
    fontSize: 12,
    color: colors.textSecondary,
    lineHeight: 16,
  },
});